services:
  mongo-dtadm:
    image: "mongo:latest"
    container_name: mongo-${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    networks:
      - data-admin
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${EXTERNAL_MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ${EXTERNAL_MONGO_DATA_IMPORT_PATH}:/docker-entrypoint-initdb.d
  mongo-express-dtadm:
    image: "mongo-express:latest"
    container_name: mongo-express-${COMPOSE_PROJECT_NAME}
    depends_on:
      - mongo-dtadm
    restart: unless-stopped
    networks:
      - data-admin
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: default
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}     
      ME_CONFIG_MONGODB_SERVER: mongo-dtadm
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
    ports:
      - ${EXTERNAL_EXPRESS_PORT}:8081
networks:
  data-admin:
    driver: bridge

